Support xpath

diff --git a/src/main/bash/velocli b/src/main/bash/velocli
--- a/src/main/bash/velocli
+++ b/src/main/bash/velocli
@@ -4,25 +4,26 @@ DIR=`dirname $0`
 
 usage() {
     echo "Usage:"
-    echo "$0 --template VELOCITY_TEMPLATE [--properties PROPERTIES]"
+    echo "$0 -t <VELOCITY_TEMPLATE> -f (prop|xml) -p <INPUT_PATH>"
 }
 
-while [ "$1" != "" ]; do
-    case "$1" in
-        --help)
+while getopts ":ht:f:p:" OPT;
+do
+    case $OPT in
+        h)
             usage
             exit 0
             ;;
-        -t|--template)
-            TEMPLATE=$2
-            shift 2
+        t)
+            TEMPLATE=$OPTARG
             ;;
-        -p|--properties)
-            PROP=$2
-            shift 2
+        f)
+            INPUT_FORMAT=$OPTARG
             ;;
-        *)
-            echo "Invalid arguments $1."
+        p)
+            INPUT_PATH=$OPTARG
+            ;;
+        ?)
             usage
             exit 1
             ;;
@@ -31,8 +32,20 @@ done
 
 if [ -z "$TEMPLATE" ]; then
     echo "VELOCITY_TEMPLATE is required." >& 2
+    echo "Try '$0 -h' for more information."
     usage
     exit 1
 fi
 
-java -jar $DIR/../lib/velocli-jar-with-dependencies.jar $TEMPLATE $PROP
+if [ -z "$INPUT_FORMAT" ]; then
+    echo "INPUT_FORMAT is required." >& 2
+    echo "Try '$0 -h' for more information."
+    usage
+    exit 1
+fi
+
+if [ -z "$INPUT_PATH" ]; then
+    INPUT_PATH="-"
+fi
+
+java -jar $DIR/../lib/velocli-jar-with-dependencies.jar $TEMPLATE $INPUT_FORMAT $INPUT_PATH
